### ISSUE TITLE
Custom Color Scheme for CoordSysRenderer

### ISSUE THREAD

**Issue by hageldave** [hageldave/JPlotter#21]
The `CoordSysRenderer` has hardcoded colors for its axes, axis-labels, ticks and guides (grid lines).
This works well with a light background color (e.g. white) but not with dark ones. It may also not integrate well into applications with a specific color scheme.

To allow for custom colors of the coordinate system elements, a color scheme class and respective setter in `CoordSysRenderer` has to be implemented.

---
A similar (and probably coupled) mechanism has to be implemented for `Legend`.

**Comment by hageldave** [comment]
I reviewed the implementation in depth and made a few changes for conciseness of the API and fixed minor bugs.
You can review the latest changes here if you like ;) https://github.com/hageldave/JPlotter/commits/customcolorscheme

**Comment by lvcarx** [comment]
Looks better i think 👍  I found a small bug in the Viz demo class, but that is fixed now. 
Can this issue be marked as closed?

**Comment by hageldave** [comment]
merged as of 5810ebfbeaa9f9aab22273f1fba5d00f3191823f

**Comment by hageldave** [comment]
For example: dark theme IrisViz
![IrisViz_dark](https://user-images.githubusercontent.com/2974361/119849709-23bcfc00-bf0d-11eb-8ac2-55e5544dbd59.png)
