### ISSUE TITLE
PDF export

### ISSUE THREAD

**Issue by hageldave** [hageldave/JPlotter#23]
JPlotter currently supports exporting to SVG through the `renderSVG(Document doc, Element parent, int w, int h)` method of `Renderer` or `SVGRenderer`.
However, SVG is incapable of shading triangles with 3 different colors (defined per vertex) i.e. interpolating barycentrically. There also seems to be an issue with triangle meshes where the edges of individual triangles are visible due to very thin gaps between adjacent triangles showing.

PDF is also capable to represent vector graphics, and also supports triangle meshes with accurate shading.
See [PDF Reference](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf) 4.6.3 > Shading Types > Type 4

To support accurate (correctly shaded) export of JPlotter visualizations as vector graphics, a 'render to PDF' functionality similar to the SVG variant needs to be implemented.

**Comment by hageldave** [comment]
PDF export functionality has been implemented and merged into master (#28). However, the PDF rendering routines lack support for use of transparent colors since they do not yet take color alpha into account.
For example the helper method for creating a linear color gradient currently ignores alpha.
https://github.com/hageldave/JPlotter/blob/8480130c4fdae5c1f77bb44fced8e9dcc14bbae0/jplotter/src/main/java/hageldave/jplotter/renderers/LinesRenderer.java#L1033

Support for transparent colors in PDF export is pending.

**Comment by hageldave** [comment]
I think most renderers are now alpha capable, except for triangles due to some complication with gouraud shading (not allowing for alpha specification of vertex colors?).
I skimmed through the PDF specification and found a section on transparency (section 7). I think we could try and use a softmask as described in section 7.4 to specify transparency for triangles. From what I understood from section 7.4.2 (_Deriving a Soft Mask from Group Luminosity_), we can create a softmask that will use the luminosity of things drawn into it as alpha. So basically we can draw the triangles in greyscale with their alpha value as grey, and then use this softmask with the actual colored triangles.

https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf#%5B%7B%22num%22%3A582%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C88%2C565%2Cnull%5D

@lvcarx what do you think? Maybe there is also a better way

**Comment by lvcarx** [comment]
Yep that solved the issue. Should be working now as expected and i will push it after some more testing. Thank you!

**Comment by hageldave** [comment]
released as of bd7cf5c
