### ISSUE TITLE
Line drawing stalls on small ranges

### ISSUE THREAD

**Issue by hageldave** [hageldave/JPlotter#41]
Extended wilkinson struggles to compute good ticks (takes very long) when the range of values is very small (e.g. xhigh-xlow < 1e-8) but values are large (e.g. xlow > 10.000).

**Comment by lvcarx** [comment]
I tried it again and it also seems to have problems with very small ranges, when both values are small (xlow = 0.0, xhigh = 4.5e-7).

**Comment by hageldave** [comment]
so we identified the problem to be in fallback line rendering, specifically this line: https://github.com/hageldave/JPlotter/blob/9af3be4189e3426238b246be27c1588912e6cd99/jplotter/src/main/java/hageldave/jplotter/renderers/LinesRenderer.java#L527
when zoomed a lot, a segments x,y coordinates can be huge (e.g. x=10^8) and we suspect this to be the problem.

The solution is to test if the segment is very long (`len>100.000`) and if that is the case, we calculate the intersection of the segment with the view rectangle, and use the intersection coordinates instead of the segment start and end coordinates.

There may be some things to be taken care of, e.g. gradient paint (color interpolation for the new segment coords) and maybe stroke pattern arguments need to be adapted.
